name:                identity-creative-rpg
version:             0.1.0.0
github:              "githubuser/identity-creative-rpg"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/identity-creative-rpg#readme>

dependencies:
- base >= 4.7 && < 5
- text
- transformers
- mtl
- containers
- random
- websockets
- stm
- lens
- vector
#- katip
- haskell-gi-base
- gi-cairo-connector
- gi-cairo-render
- gi-cairo
- gi-gtk >= 4.0.5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
  OverloadedStrings
  OverloadedLabels
  ImplicitParams
  BlockArguments

library:
  source-dirs: src

executables:
  identity-creative-rpg-client:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - identity-creative-rpg
  identity-creative-rpg-server:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - identity-creative-rpg

tests:
  identity-creative-rpg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - identity-creative-rpg
